import { api } from "/components/api.js";
import {
  fmtTime,
  fmtTimeAbsolute,
  loadingSkeleton,
  severityChip,
  emptyState,
  escapeHtml,
  toast,
} from "/components/ui.js";

function ringColor(score) {
  if (score >= 70) return "var(--red)";
  if (score >= 30) return "var(--amber)";
  return "var(--green)";
}

export async function renderInsights(view) {
  view.innerHTML = `<div class="glass card fade-in">${loadingSkeleton(4)}</div>`;

  let latest, history;
  try {
    [latest, history] = await Promise.all([
      api.latestInsight(),
      api.listInsights(20),
    ]);
  } catch (e) {
    toast(`Failed to load insights: ${e.message}`, "error");
    return;
  }

  const score = latest?.risk_score ?? 0;
  const anomalies = latest?.anomalies || [];
  const recos = latest?.recommendations || [];

  view.innerHTML = `
    <div class="grid cols-2 fade-in" style="grid-template-columns:1.1fr 1fr">
      <div class="glass card">
        <h2>Latest AI Analysis</h2>
        <div class="h-sub">Generated by the rule-based engine${latest?.source==="openai"?" + OpenAI refinement":""}.</div>
        <div class="gauge" style="margin-top:8px">
          <div class="gauge-ring" style="--p:${score};--ring-color:${ringColor(score)}">
            <div class="num" style="color:${ringColor(score)}">${score}</div>
            <div class="lbl">/ 100</div>
          </div>
          <div class="gauge-meta">
            <div class="h">Summary</div>
            <div class="t" style="font-size:14.5px;line-height:1.55;font-weight:500">
              ${escapeHtml(latest?.summary || "No analysis yet — trigger a scan to populate insights.")}
            </div>
            <div class="row" style="margin-top:6px;flex-wrap:wrap;gap:6px">
              <span class="chip muted">${latest?.devices_total ?? 0} devices</span>
              <span class="chip muted">${latest?.devices_failed ?? 0} failed</span>
              <span class="chip muted">${anomalies.length} anomalies</span>
            </div>
          </div>
        </div>
      </div>

      <div class="glass card">
        <h2>Recommendations</h2>
        <div class="h-sub">Suggested actions based on current conditions.</div>
        ${recos.length ? `<ol class="recos" style="margin:0;padding-left:20px">
          ${recos.map(r=>`<li>${escapeHtml(r)}</li>`).join("")}
        </ol>` : emptyState("✓","No active recommendations.")}
      </div>
    </div>

    <div class="glass card fade-in" style="margin-top:18px">
      <h2>Detected Anomalies</h2>
      <div class="h-sub">Issues identified by analyzing the most recent scan and 24h history.</div>
      ${anomalies.length ? `<div class="anomalies">
        ${anomalies.map(a => `<div class="anomaly">
          <div class="ico ${a.severity || 'info'}">!</div>
          <div>
            <div style="font-weight:600">${escapeHtml(a.type || 'anomaly').replace(/_/g,' ')}</div>
            <div class="muted small">${escapeHtml(a.message || '')}</div>
          </div>
          <div style="text-align:right">
            ${severityChip(a.severity)}
            <div class="target" style="margin-top:4px">${escapeHtml(a.target || '')}</div>
          </div>
        </div>`).join("")}
      </div>` : emptyState("✦","No anomalies detected. Network appears stable.")}
    </div>

    <div class="glass card fade-in" style="margin-top:18px">
      <h2>Insight History</h2>
      <div class="h-sub">Risk score timeline across recent scans</div>
      ${renderHistory(history)}
    </div>
  `;
}

function renderHistory(history) {
  if (!history?.length) return emptyState("∿", "No insight history yet");
  // Simple inline sparkline using a flexbox of bars + table.
  const maxScore = 100;
  const bars = `<div style="display:flex;align-items:end;gap:4px;height:80px;margin:8px 0 14px">
    ${history.slice().reverse().map(h => {
      const h_pct = (h.risk_score / maxScore) * 100;
      const color = h.risk_score >= 70 ? "var(--red)" :
                    h.risk_score >= 30 ? "var(--amber)" : "var(--green)";
      return `<div title="${h.risk_score} — ${fmtTimeAbsolute(h.created_at)}"
              style="flex:1;height:${Math.max(4,h_pct)}%;background:${color};opacity:0.8;border-radius:4px 4px 0 0"></div>`;
    }).join("")}
  </div>`;
  return bars + `<table class="table">
    <thead><tr><th>When</th><th>Risk</th><th>Devices</th><th>Anomalies</th><th>Source</th></tr></thead>
    <tbody>
      ${history.map(h => `<tr>
        <td class="muted small" title="${fmtTimeAbsolute(h.created_at)}">${fmtTime(h.created_at)}</td>
        <td><strong style="color:${h.risk_score>=70?'var(--red)':h.risk_score>=30?'var(--amber)':'var(--green)'}">${h.risk_score}</strong></td>
        <td>${h.devices_total} (${h.devices_failed} failed)</td>
        <td>${(h.anomalies||[]).length}</td>
        <td><span class="chip muted">${escapeHtml(h.source)}</span></td>
      </tr>`).join("")}
    </tbody>
  </table>`;
}
